remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  toc_levels: 1..3

url: https://sluglang.org
baseurl: ""

title: Slug
description: a small opinionated programming language!
