remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

url: https://sluglang.org
baseurl: ""

title: Slug
description: a small opinionated programming language!

toc:
  min_level: 1
  max_level: 3
