remote_theme: dieghernan/chulapa

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

markdown: kramdown
kramdown:
  toc_levels: 1..3

url: https://sluglang.org
baseurl: ""

title: Slug
description: a small opinionated programming language!
repository: https://github.com/babyman/slug-lang

og_image: /assets/no_shell.jpeg

author:
  name: Knuckles

#chulapa-skin:
#  skin: twitter-dim
#  highlight: coffee

navbar:
  style: classic
  brand:
    title: Slug
    #    img: "./assets/img/site/brand-clear.png"
    url: /
  nav:
    - title: ADRs #Label
      url: /adrs.html  #url
#    - title: Two-level link #Label
#      child:
#        - title: Second level first item
#          url: /url2-1
#        - title: Second level second item
#          url: /url2-2
#    - title: One-level link #Label
#      url: /url1/  #url
#        ... more levels

collections:
#  demo:
#    output: true
#    permalink: /demo/:name
  adrs:
    output: true
#    permalink: /adr/:name
#  skins:
#    output: true
#    permalink: /skins/:name
#collections_dir     : docs/collections
#permalink           : /:year:month:day_:title/
