remote_theme: dieghernan/chulapa

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-sitemap
  - jemoji

title: Slug
description: a small opinionated programming language!
url: https://sluglang.org
#baseurl: ""
repository: babyman/slug-lang
og_image: /assets/no_shell.jpeg

markdown: kramdown
kramdown:
  toc_levels: 1..3

author:
  name: Knuckles
  avatar: /assets/knuckles-avatar.png
  location: Toronto, Canada

chulapa-skin:
  skin: butterfly
  highlight: default

navbar:
  style: dual
  brand:
    title: Home
#    img: "./assets/img/site/brand-clear.png"
    url: /
  nav:
    - title: Setup
      url: /setup/
    - title: Developers Guide
      url: /developers-guide.html
    - title: Cookbook
      url: /cookbook/
    - title: ADRs
      url: /adr/
    - title: GitHub
      url: https://github.com/babyman/slug-lang/

footer:
  links:
    - label: "RSS"
      icon: "fa fa-rss"
      url: "./atom.xml"
    - label: "GitHub"
      icon: "fab fa-github"
      url: https://github.com/babyman/slug-lang/

collections:
  adr:
    output: true
    permalink: /adr/:name
  cookbook:
    output: true
    permalink: /cookbook/:name

# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      show_breadcrumb: true
      breadcrumb_list:
        - label: Home
          url: /
  - scope:
      path: ""
      type: "adr"
    values:
      header_type: post
      breadcrumb_list:
        - label: Home
          url: /
        - label: Architectural Design Records
          url: /adr/
  - scope:
      path: ""
      type: "cookbook"
    values:
      header_type: post
      include_on_search : true
      include_on_feed   : true
      show_date         : false
      show_related      : true
      show_tags         : false
      show_author       : true
      breadcrumb_list:
        - label: Home
          url: /
        - label: Cookbook
          url: /cookbook/


# Exclude these files from production site
exclude:
  - README.md
  - Gemfile
