name: build-test-tag-and-release

on:
  push:
    branches: [ "master" ]
    paths:
      - 'VERSION'
      - '**.go'
      - '**.slug'

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.x'

      - name: Set SLUG_HOME
        run: |
          echo "SLUG_HOME=$(pwd)" >> $GITHUB_ENV

      - name: Build and test
        timeout-minutes: 5
        run: |
          echo "Using SLUG_HOME=$SLUG_HOME"
          make test

      - name: Tag build version
        run: |
          V="$(cat VERSION)"
          VERSION="v${V}-b${{ github.run_number }}"
          echo "Tagging with verson $VERSION"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"

      - name: Release
        uses: goreleaser/goreleaser-action@v6.4.0
        with:
          distribution: goreleaser
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
